+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 19:19:32 2023 - INFO  - Start to run test.
+ ssh_cmd_node 'raw /dev/raw/raw1 1 1'
+ cmd='raw /dev/raw/raw1 1 1'
+ SSH_CMD 'raw /dev/raw/raw1 1 1' 10.198.114.4 'openEuler12#$' root
+ cmd='raw /dev/raw/raw1 1 1'
+ remoteip=10.198.114.4
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'raw /dev/raw/raw1 1 1' -i 10.198.114.4 -u root -p 'openEuler12#$' -t 300 -o 22
Wed May  3 19:19:33 2023 - WARN  - the remote user uses the default configuration.
Wed May  3 19:19:33 2023 - WARN  - the remote password uses the default configuration.
Wed May  3 19:19:33 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.4 raw /dev/raw/raw1 1 1
The authenticity of host '10.198.114.4 (10.198.114.4)' can't be established.
ED25519 key fingerprint is SHA256:M6IZ/zy3MxMo6/o/fy+aY4RQYnH9M5BZVPilD5Busik.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.198.114.4' (ED25519) to the list of known hosts.

Authorized users only. All activities may be monitored and reported.
root@10.198.114.4's password: 
bash: line 1: raw: command not found
+ ret=127
+ test 127 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:127'
+ message='Failed in remote CMD operation:127'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:127'
Wed May  3 19:19:35 2023 - ERROR - Failed in remote CMD operation:127
+ return 127
+ CHECK_RESULT 127 0 0 'Create /dev/raw/raw1 failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Create /dev/raw/raw1 failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Create /dev/raw/raw1 failed.'
+ LOG_ERROR 'Create /dev/raw/raw1 failed.'
+ message='Create /dev/raw/raw1 failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Create /dev/raw/raw1 failed.'
Wed May  3 19:19:35 2023 - ERROR - Create /dev/raw/raw1 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raw_reboot.sh line 24'
+ message='oe_test_raw_reboot.sh line 24'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raw_reboot.sh line 24'
Wed May  3 19:19:36 2023 - ERROR - oe_test_raw_reboot.sh line 24
+ '[' 0 -eq 1 ']'
+ return 0
+ ssh_cmd_node 'blockdev --report /dev/raw/raw1'
+ cmd='blockdev --report /dev/raw/raw1'
+ SSH_CMD 'blockdev --report /dev/raw/raw1' 10.198.114.4 'openEuler12#$' root
+ cmd='blockdev --report /dev/raw/raw1'
+ remoteip=10.198.114.4
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'blockdev --report /dev/raw/raw1' -i 10.198.114.4 -u root -p 'openEuler12#$' -t 300 -o 22
Wed May  3 19:19:36 2023 - WARN  - the remote user uses the default configuration.
Wed May  3 19:19:36 2023 - WARN  - the remote password uses the default configuration.
Wed May  3 19:19:37 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.4 blockdev --report /dev/raw/raw1

Authorized users only. All activities may be monitored and reported.
root@10.198.114.4's password: 
blockdev: cannot open /dev/raw/raw1RO    RA   SSZ   BSZ        StartSec            Size   Device
: No such file or directory
+ ret=0
+ test 0 -ne 0
+ return 0
+ CHECK_RESULT 0 0 0 'Check report for /dev/raw/raw1 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check report for /dev/raw/raw1 failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ssh_cmd_node 'raw -qa | grep /dev/raw/raw1'
+ cmd='raw -qa | grep /dev/raw/raw1'
+ SSH_CMD 'raw -qa | grep /dev/raw/raw1' 10.198.114.4 'openEuler12#$' root
+ cmd='raw -qa | grep /dev/raw/raw1'
+ remoteip=10.198.114.4
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'raw -qa | grep /dev/raw/raw1' -i 10.198.114.4 -u root -p 'openEuler12#$' -t 300 -o 22
Wed May  3 19:19:38 2023 - WARN  - the remote user uses the default configuration.
Wed May  3 19:19:39 2023 - WARN  - the remote password uses the default configuration.
Wed May  3 19:19:39 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.4 raw -qa | grep /dev/raw/raw1

Authorized users only. All activities may be monitored and reported.
root@10.198.114.4's password: 
bash: line 1: raw: command not found
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Wed May  3 19:19:40 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0 'Check /dev/raw/raw1 failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check /dev/raw/raw1 failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check /dev/raw/raw1 failed.'
+ LOG_ERROR 'Check /dev/raw/raw1 failed.'
+ message='Check /dev/raw/raw1 failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check /dev/raw/raw1 failed.'
Wed May  3 19:19:41 2023 - ERROR - Check /dev/raw/raw1 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raw_reboot.sh line 28'
+ message='oe_test_raw_reboot.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raw_reboot.sh line 28'
Wed May  3 19:19:41 2023 - ERROR - oe_test_raw_reboot.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ REMOTE_REBOOT 2
+ node=2
+ waittime=
+ '[' x '!=' x ']'
+ python3 /root/mugen/libs/locallibs/remote_reboot.py reboot --node 2
Wed May  3 19:49:31 2023 - ERROR - Timeout : Command 'bash -x oe_test_raw_reboot.sh' timed out after 1799.9997478000003 seconds
