+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Apr 27 12:14:27 2023 - INFO  - Start to prepare the test environment.
+ rmMessage=1
+ '[' -e /var/log/messages ']'
+ /etc/init.d/syslog restart
oe_test_system_log_logrotate.sh: line 29: /etc/init.d/syslog: No such file or directory
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu Apr 27 12:14:28 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Apr 27 12:14:29 2023 - INFO  - Start to run test.
+ ls /var/log/messages
ls: cannot access '/var/log/messages': No such file or directory
+ CHECK_RESULT 2 0 0 'check /var/log/messages fail'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='check /var/log/messages fail'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'check /var/log/messages fail'
+ LOG_ERROR 'check /var/log/messages fail'
+ message='check /var/log/messages fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check /var/log/messages fail'
Thu Apr 27 12:14:30 2023 - ERROR - check /var/log/messages fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_system_log_logrotate.sh line 38'
+ message='oe_test_system_log_logrotate.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_system_log_logrotate.sh line 38'
Thu Apr 27 12:14:31 2023 - ERROR - oe_test_system_log_logrotate.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -rf '/var/log/messages-*.gz'
+ mv /etc/logrotate.d/rsyslog /etc/logrotate.d/rsyslog_bak
mv: cannot stat '/etc/logrotate.d/rsyslog': No such file or directory
+ cat
+ logrotate -f /etc/logrotate.d/rsyslog
error: stat of /var/log/messages failed: No such file or directory
+ CHECK_RESULT 1 0 0 'check logrotate fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check logrotate fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check logrotate fail'
+ LOG_ERROR 'check logrotate fail'
+ message='check logrotate fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check logrotate fail'
Thu Apr 27 12:14:32 2023 - ERROR - check logrotate fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_system_log_logrotate.sh line 56'
+ message='oe_test_system_log_logrotate.sh line 56'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_system_log_logrotate.sh line 56'
Thu Apr 27 12:14:32 2023 - ERROR - oe_test_system_log_logrotate.sh line 56
+ '[' 0 -eq 1 ']'
+ return 0
+ ls '/var/log/messages-*.gz'
ls: cannot access '/var/log/messages-*.gz': No such file or directory
+ CHECK_RESULT 2 0 0 'check messages-*.gz fail'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='check messages-*.gz fail'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'check messages-*.gz fail'
+ LOG_ERROR 'check messages-*.gz fail'
+ message='check messages-*.gz fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check messages-*.gz fail'
Thu Apr 27 12:14:33 2023 - ERROR - check messages-*.gz fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_system_log_logrotate.sh line 58'
+ message='oe_test_system_log_logrotate.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_system_log_logrotate.sh line 58'
Thu Apr 27 12:14:34 2023 - ERROR - oe_test_system_log_logrotate.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Apr 27 12:14:35 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Apr 27 12:14:36 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Apr 27 12:14:37 2023 - INFO  - Start to restore the test environment.
+ rm -rf /etc/logrotate.d/rsyslog
+ mv /etc/logrotate.d/rsyslog_bak /etc/logrotate.d/rsyslog
mv: cannot stat '/etc/logrotate.d/rsyslog_bak': No such file or directory
+ '[' 1 -eq 1 ']'
+ rm -rf /var/log/messages
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Apr 27 12:14:38 2023 - INFO  - End to restore the test environment.
