+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start loading data!'
+ message='Start loading data!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start loading data!'
Fri Apr 28 09:33:33 2023 - INFO  - Start loading data!
++ lsblk
++ grep disk
++ awk '{print$1}'
++ sed -n 2p
+ remote_disk=vdb
+ LOG_INFO 'Loading data is complete!'
+ message='Loading data is complete!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Loading data is complete!'
Fri Apr 28 09:33:34 2023 - INFO  - Loading data is complete!
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Fri Apr 28 09:33:35 2023 - INFO  - Start environment preparation.
+ DNF_INSTALL nfs-utils
+ pkgs=nfs-utils
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs nfs-utils --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpnr3c7tdx
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpnr3c7tdx
+ systemctl stop firewalld
Failed to stop firewalld.service: Unit firewalld.service not loaded.
+ iptables -F
+ SSH_CMD 'systemctl stop firewalld;iptables -F' 10.198.114.3 'openEuler12#$' root
+ cmd='systemctl stop firewalld;iptables -F'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl stop firewalld;iptables -F' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, 100% packet loss, time 0ms
Fri Apr 28 09:34:48 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 09:34:49 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Fri Apr 28 09:34:50 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Fri Apr 28 09:34:51 2023 - INFO  - Start executing testcase.
+ SSH_CMD 'yum install nfs-utils -y;mkdir /home/nfs;mv /etc/exports /etc/exports.bak;
	echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports; exportfs -avr' 10.198.114.3 'openEuler12#$' root
+ cmd='yum install nfs-utils -y;mkdir /home/nfs;mv /etc/exports /etc/exports.bak;
	echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports; exportfs -avr'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'yum install nfs-utils -y;mkdir /home/nfs;mv /etc/exports /etc/exports.bak;
	echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports; exportfs -avr' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 09:34:52 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 09:34:53 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 09:34:54 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 yum install nfs-utils -y;mkdir /home/nfs;mv /etc/exports /etc/exports.bak;
	echo '/home/nfs *(rw,sync,all_squash)' >/etc/exports; exportfs -avr
ssh: connect to host 10.198.114.3 port 22: Connection timed out
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:255'
+ message='Failed in remote CMD operation:255'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:255'
Fri Apr 28 09:37:04 2023 - ERROR - Failed in remote CMD operation:255
+ return 255
+ CHECK_RESULT 255
+ actual_result=255
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 255 ']'
+ '[' 0 -eq 0 ']'
+ test 255x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_write_full.sh line 40'
+ message='oe_test_storage_nfs_write_full.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_write_full.sh line 40'
Fri Apr 28 09:37:05 2023 - ERROR - oe_test_storage_nfs_write_full.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_CMD 'systemctl restart nfs-server rpcbind;mkfs.ext4 -F /dev/vdb;
	mount /dev/vdb /home/nfs;chmod -R 777 /home/nfs' 10.198.114.3 'openEuler12#$' root
+ cmd='systemctl restart nfs-server rpcbind;mkfs.ext4 -F /dev/vdb;
	mount /dev/vdb /home/nfs;chmod -R 777 /home/nfs'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl restart nfs-server rpcbind;mkfs.ext4 -F /dev/vdb;
	mount /dev/vdb /home/nfs;chmod -R 777 /home/nfs' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 09:37:07 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 09:37:07 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 09:37:08 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 systemctl restart nfs-server rpcbind;mkfs.ext4 -F /dev/vdb;
	mount /dev/vdb /home/nfs;chmod -R 777 /home/nfs
root@10.198.114.3's password: 
Failed to restart nfs-server.service: Unit nfs-server.service not found.
Warning: The unit file, source configuration file or drop-ins of rpcbind.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for rpcbind.service failed because of unavailable resources or another system error.
See "systemctl status rpcbind.service" and "journalctl -xeu rpcbind.service" for details.
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:      0/512000             done                            
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: eff87cfb-0d3c-494e-b7a8-b6b61e7b03ad
Superblock backups stored on blocks: 
	8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables:  0/63     done                            
Writing inode tables:  0/63     done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information:  0/63     done

mount: /home/nfs: mount point does not exist.
chmod: cannot access '/home/nfs': No such file or directory
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Apr 28 09:37:22 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_write_full.sh line 43'
+ message='oe_test_storage_nfs_write_full.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_write_full.sh line 43'
Fri Apr 28 09:37:22 2023 - ERROR - oe_test_storage_nfs_write_full.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ mkdir /home/client
+ chmod 777 -R /home/client
+ systemctl restart nfs-server rpcbind
+ mount -t nfs 10.198.114.3:/home/nfs /home/client
mount.nfs: Connection refused
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_write_full.sh line 48'
+ message='oe_test_storage_nfs_write_full.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_write_full.sh line 48'
Fri Apr 28 09:39:36 2023 - ERROR - oe_test_storage_nfs_write_full.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 10.198.114.3
+ df -h
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_write_full.sh line 50'
+ message='oe_test_storage_nfs_write_full.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_write_full.sh line 50'
Fri Apr 28 09:39:37 2023 - ERROR - oe_test_storage_nfs_write_full.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_CMD 'dd if=/dev/zero of=/home/nfs/test bs=1k count=1' 10.198.114.3 'openEuler12#$' root
+ cmd='dd if=/dev/zero of=/home/nfs/test bs=1k count=1'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'dd if=/dev/zero of=/home/nfs/test bs=1k count=1' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, 100% packet loss, time 0ms
Fri Apr 28 09:39:48 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 09:39:49 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ dd if=/dev/zero of=/home/client/test1 bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0466599 s, 22.5 MB/s
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SSH_CMD 'rm -rf /home/nfs/*' 10.198.114.3 'openEuler12#$' root
+ cmd='rm -rf /home/nfs/*'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'rm -rf /home/nfs/*' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, 100% packet loss, time 2ms
Fri Apr 28 09:40:00 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 09:40:01 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ SLEEP_WAIT 2
+ wait_time=2
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 2 --cmd '' --mode 1
+ dd if=/dev/zero of=/home/client/test1 bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0559496 s, 18.7 MB/s
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End of testcase execution.'
+ message='End of testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution.'
Fri Apr 28 09:40:05 2023 - INFO  - End of testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Apr 28 09:40:06 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Apr 28 09:40:06 2023 - INFO  - start environment cleanup.
+ umount /home/client
umount: /home/client: not mounted.
+ SLEEP_WAIT 2
+ wait_time=2
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 2 --cmd '' --mode 1
+ SSH_CMD 'umount /home/nfs;rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports;
    umount /home/nfs; systemctl start firewalld' 10.198.114.3 'openEuler12#$' root
+ cmd='umount /home/nfs;rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports;
    umount /home/nfs; systemctl start firewalld'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'umount /home/nfs;rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports;
    umount /home/nfs; systemctl start firewalld' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, 100% packet loss, time 1ms
Fri Apr 28 09:40:20 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 09:40:21 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ rmdir /home/client
rmdir: failed to remove '/home/client': Directory not empty
+ systemctl start firewalld
Failed to start firewalld.service: Unit firewalld.service not found.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpnr3c7tdx ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpnr3c7tdx
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Fri Apr 28 09:40:51 2023 - INFO  - Finish environment cleanup.
