+ source ../common/common_ndisc6.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed May  3 20:09:23 2023 - INFO  - Start to prepare the test environment.
+ deploy_env
+ DNF_INSTALL 'ndisc6 xinetd time'
+ pkgs='ndisc6 xinetd time'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'ndisc6 xinetd time' --node 1 --tempfile ''
Wed May  3 20:09:27 2023 - INFO  - pkgs:(ndisc6 xinetd time) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
++ hostname
../common/common_ndisc6.sh: line 21: hostname: command not found
+ hostname_init=
+ hostname newlocalhost
../common/common_ndisc6.sh: line 22: hostname: command not found
++ ip addr show 10.198.114.191
++ grep -w inet6
++ awk '{print $2}'
++ awk 'NR==1{print $1}'
++ awk -F / '{print $1}'
Device "10.198.114.191" does not exist.
+ NODE1_IPV6=
++ P_SSH_CMD --node 2 --cmd 'ip addr show ens4'
++ python3 /root/mugen/libs/locallibs/ssh_cmd.py --node 2 --cmd 'ip addr show ens4'
++ grep -w inet6
++ awk '{print $2}'
++ awk 'NR==1{print $1}'
++ awk -F / '{print $1}'
+ NODE2_IPV6=fe80::3afe:c976:9125:1e46
+ cp /etc/resolv.conf /etc/resolv.conf-bak
+ sed -i 's/name/#&/' /etc/resolv.conf
+ sed -i 6s/yes/no/g /etc/xinetd.d/echo-stream
+ systemctl restart xinetd
+ DNF_INSTALL xinetd 2
+ pkgs=xinetd
+ node=2
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs xinetd --node 2 --tempfile ''
Wed May  3 20:09:35 2023 - INFO  - pkgs:(xinetd) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ P_SSH_CMD --node 2 --cmd 'sed -i '\''6s/yes/no/g'\'' /etc/xinetd.d/echo-stream;systemctl restart xinetd;'
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --node 2 --cmd 'sed -i '\''6s/yes/no/g'\'' /etc/xinetd.d/echo-stream;systemctl restart xinetd;'

+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed May  3 20:09:38 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 20:09:38 2023 - INFO  - Start to run test.
+ name2addr -4 newlocalhost
+ grep 10.198.114.1
newlocalhost: Name or service not known
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ndisc6_name2addr.sh line 29'
+ message='oe_test_ndisc6_name2addr.sh line 29'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ndisc6_name2addr.sh line 29'
Wed May  3 20:09:38 2023 - ERROR - oe_test_ndisc6_name2addr.sh line 29
+ '[' 0 -eq 1 ']'
+ return 0
+ name2addr -6 newlocalhost
+ grep ''
newlocalhost: Name or service not known
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ndisc6_name2addr.sh line 31'
+ message='oe_test_ndisc6_name2addr.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ndisc6_name2addr.sh line 31'
Wed May  3 20:09:38 2023 - ERROR - oe_test_ndisc6_name2addr.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ name2addr -c newlocalhost
+ grep 10.198.114.191
newlocalhost: Name or service not known
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ndisc6_name2addr.sh line 33'
+ message='oe_test_ndisc6_name2addr.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ndisc6_name2addr.sh line 33'
Wed May  3 20:09:39 2023 - ERROR - oe_test_ndisc6_name2addr.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ name2addr -m localhost newlocalhost
+ grep -E '10.198.114.1|'
newlocalhost: Name or service not known
::1 127.0.0.1
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ name2addr -n -r 10.198.114.1
+ grep newlocalhost
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ndisc6_name2addr.sh line 37'
+ message='oe_test_ndisc6_name2addr.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ndisc6_name2addr.sh line 37'
Wed May  3 20:09:39 2023 - ERROR - oe_test_ndisc6_name2addr.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ name2addr -n -r
+ grep newlocalhost
Wed May  3 20:39:22 2023 - ERROR - Timeout : Command 'bash -x oe_test_ndisc6_name2addr.sh' timed out after 1799.99949145 seconds
++ post_test
++ LOG_INFO 'Start to restore the test environment.'
++ message='Start to restore the test environment.'
++ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 20:42:26 2023 - INFO  - Start to restore the test environment.
++ clear_env
++ DNF_REMOVE
++ node=1
++ pkg_list=
++ mode=0
++ [[ -z '' ]]
++ [[ -z '' ]]
++ LOG_WARN 'no thing to do.'
++ message='no thing to do.'
++ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed May  3 20:42:27 2023 - WARN  - no thing to do.
++ return 0
++ hostname
../common/common_ndisc6.sh: line 35: hostname: command not found
++ cp -rf /etc/resolv.conf-bak /etc/resolv.conf
cp: cannot stat '/etc/resolv.conf-bak': No such file or directory
++ rm -rf file runtime /etc/resolv.conf-bak
++ LOG_INFO 'End to restore the test environment.'
++ message='End to restore the test environment.'
++ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed May  3 20:42:27 2023 - INFO  - End to restore the test environment.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ndisc6_name2addr.sh line 39'
+ message='oe_test_ndisc6_name2addr.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ndisc6_name2addr.sh line 39'
Wed May  3 20:42:27 2023 - ERROR - oe_test_ndisc6_name2addr.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
++ rpm -qa ndisc6
++ awk -F - '{print $2}'
+ ndisc6_version=1.0.4
+ name2addr -V
+ grep 1.0.4
addrinfo 1.0.4 ($Rev$)
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ name2addr -h
+ grep name2addr
Usage: name2addr [-4|-6] [hostnames]
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ echo 'hello world'
+ dnssort -r file
+ grep 'hello world'
hello world
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed May  3 20:42:28 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed May  3 20:42:29 2023 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 20:42:29 2023 - INFO  - Start to restore the test environment.
+ clear_env
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed May  3 20:42:29 2023 - WARN  - no thing to do.
+ return 0
+ hostname
../common/common_ndisc6.sh: line 35: hostname: command not found
+ cp -rf /etc/resolv.conf-bak /etc/resolv.conf
cp: cannot stat '/etc/resolv.conf-bak': No such file or directory
+ rm -rf file runtime /etc/resolv.conf-bak
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed May  3 20:42:30 2023 - INFO  - End to restore the test environment.
