+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230428135238 /tmp/point220230428135238 /tmp/point320230428135238
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Apr 28 13:53:27 2023 - INFO  - Start to prepare the database config.
++ TEST_DISK 2
++ id=2
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 2
Fri Apr 28 13:53:31 2023 - ERROR - Failed to connect the remote machine:10.198.114.3.
Fri Apr 28 13:53:31 2023 - ERROR - [Errno None] Unable to connect to port 22 on 10.198.114.3
+ test_disk=/dev/
+ ssh_cmd_node 'cp /etc/fstab /etc/fstab.bak'
+ cmd='cp /etc/fstab /etc/fstab.bak'
+ SSH_CMD 'cp /etc/fstab /etc/fstab.bak' 10.198.114.3 'openEuler12#$' root
+ cmd='cp /etc/fstab /etc/fstab.bak'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'cp /etc/fstab /etc/fstab.bak' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Apr 28 13:53:35 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 13:53:36 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ ssh_cmd_node 'fdisk /dev/ << diskEof
n
p
1

100000
w
diskEof'
+ cmd='fdisk /dev/ << diskEof
n
p
1

100000
w
diskEof'
+ SSH_CMD 'fdisk /dev/ << diskEof
n
p
1

100000
w
diskEof' 10.198.114.3 'openEuler12#$' root
+ cmd='fdisk /dev/ << diskEof
n
p
1

100000
w
diskEof'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'fdisk /dev/ << diskEof
n
p
1

100000
w
diskEof' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Apr 28 13:53:39 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 13:53:40 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ dmname=/dev/1
+ ssh_cmd_node 'mkswap /dev/1'
+ cmd='mkswap /dev/1'
+ SSH_CMD 'mkswap /dev/1' 10.198.114.3 'openEuler12#$' root
+ cmd='mkswap /dev/1'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'mkswap /dev/1' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Apr 28 13:53:44 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 13:53:44 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Apr 28 13:53:45 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 13:53:46 2023 - INFO  - Start to run test.
+ ssh_cmd_node 'echo '\''/dev/1 swap swap defaults 0 0'\'' >> /etc/fstab'
+ cmd='echo '\''/dev/1 swap swap defaults 0 0'\'' >> /etc/fstab'
+ SSH_CMD 'echo '\''/dev/1 swap swap defaults 0 0'\'' >> /etc/fstab' 10.198.114.3 'openEuler12#$' root
+ cmd='echo '\''/dev/1 swap swap defaults 0 0'\'' >> /etc/fstab'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'echo '\''/dev/1 swap swap defaults 0 0'\'' >> /etc/fstab' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Apr 28 13:53:48 2023 - ERROR - connection to 10.198.114.3 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Apr 28 13:53:48 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ CHECK_RESULT 101 0 0 'Add mount swap on /etc/fstab failed.'
+ actual_result=101
+ expect_result=0
+ mode=0
+ error_log='Add mount swap on /etc/fstab failed.'
+ exit_mode=0
+ '[' -z 101 ']'
+ '[' 0 -eq 0 ']'
+ test 101x '!=' 0x
+ test -n 'Add mount swap on /etc/fstab failed.'
+ LOG_ERROR 'Add mount swap on /etc/fstab failed.'
+ message='Add mount swap on /etc/fstab failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mount swap on /etc/fstab failed.'
Fri Apr 28 13:53:49 2023 - ERROR - Add mount swap on /etc/fstab failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_swap_auto_mount.sh line 41'
+ message='oe_test_swap_auto_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_swap_auto_mount.sh line 41'
Fri Apr 28 13:53:50 2023 - ERROR - oe_test_swap_auto_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ REMOTE_REBOOT 2 180
+ node=2
+ waittime=180
+ '[' 180x '!=' x ']'
+ python3 /root/mugen/libs/locallibs/remote_reboot.py reboot --node 2 --waittime 180
Fri Apr 28 13:53:55 2023 - ERROR - Failed to connect the remote machine:10.198.114.3.
Fri Apr 28 13:53:55 2023 - ERROR - [Errno None] Unable to connect to port 22 on 10.198.114.3
Fri Apr 28 13:53:55 2023 - ERROR - 
+ REMOTE_REBOOT_WAIT 2 180
+ node=2
+ waittime=180
+ '[' 180x '!=' x ']'
+ python3 /root/mugen/libs/locallibs/remote_reboot.py wait --node 2 --waittime 180
Fri Apr 28 14:23:23 2023 - ERROR - Timeout : Command 'bash -x oe_test_swap_auto_mount.sh' timed out after 1799.9991437030003 seconds
