+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ grep test_vggroup
++ lsblk
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230428122339 /tmp/point220230428122339 /tmp/point320230428122339
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Apr 28 12:54:13 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL mdadm 2
+ pkgs=mdadm
+ node=2
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs mdadm --node 2 --tempfile ''
Fri Apr 28 12:54:38 2023 - INFO  - pkgs:(mdadm) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
++ TEST_DISK 2
++ id=2
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 2
+ test_disk='/dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt'
+ ssh_cmd_node 'mkdir /mnt/test_md'
+ cmd='mkdir /mnt/test_md'
+ SSH_CMD 'mkdir /mnt/test_md' 10.198.114.3 'openEuler12#$' root
+ cmd='mkdir /mnt/test_md'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'mkdir /mnt/test_md' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:54:49 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:54:49 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:54:50 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 mkdir /mnt/test_md
The authenticity of host '10.198.114.3 (10.198.114.3)' can't be established.
ED25519 key fingerprint is SHA256:j2wdRtPc00KLhvK3Tj+SkYkwB1FXdanKLflYeFA0yE8.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.198.114.3' (ED25519) to the list of known hosts.
root@10.198.114.3's password: 
+ ret=0
+ test 0 -ne 0
+ return 0
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Apr 28 12:54:55 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 12:54:56 2023 - INFO  - Start to run test.
+ for fs in ${FS_TYPE[@]}
+ ssh_cmd_node 'cp /etc/fstab /etc/fstab.bak'
+ cmd='cp /etc/fstab /etc/fstab.bak'
+ SSH_CMD 'cp /etc/fstab /etc/fstab.bak' 10.198.114.3 'openEuler12#$' root
+ cmd='cp /etc/fstab /etc/fstab.bak'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'cp /etc/fstab /etc/fstab.bak' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:54:57 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:54:58 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:54:59 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 cp /etc/fstab /etc/fstab.bak
root@10.198.114.3's password: 
+ ret=0
+ test 0 -ne 0
+ return 0
+ ssh_cmd_node 'fdisk /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt << diskEof
n
p
1

+100M
Y
n
p
2

+100M
Y
w
diskEof'
+ cmd='fdisk /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt << diskEof
n
p
1

+100M
Y
n
p
2

+100M
Y
w
diskEof'
+ SSH_CMD 'fdisk /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt << diskEof
n
p
1

+100M
Y
n
p
2

+100M
Y
w
diskEof' 10.198.114.3 'openEuler12#$' root
+ cmd='fdisk /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt << diskEof
n
p
1

+100M
Y
n
p
2

+100M
Y
w
diskEof'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'fdisk /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt << diskEof
n
p
1

+100M
Y
n
p
2

+100M
Y
w
diskEof' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:04 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:05 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:55:06 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 fdisk /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt << diskEof
n
p
1

+100M
Y
n
p
2

+100M
Y
w
diskEof
root@10.198.114.3's password: 
fdisk: bad usage
Try 'fdisk --help' for more information.
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Apr 28 12:55:10 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'mdadm --stop /dev/md0'
+ cmd='mdadm --stop /dev/md0'
+ SSH_CMD 'mdadm --stop /dev/md0' 10.198.114.3 'openEuler12#$' root
+ cmd='mdadm --stop /dev/md0'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'mdadm --stop /dev/md0' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:12 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:12 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:55:13 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 mdadm --stop /dev/md0
root@10.198.114.3's password: 
mdadm: error opening /dev/md0: No such file or directory
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Apr 28 12:55:18 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ ssh_cmd_node 'echo y | mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt1 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt2'
+ cmd='echo y | mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt1 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt2'
+ SSH_CMD 'echo y | mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt1 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt2' 10.198.114.3 'openEuler12#$' root
+ cmd='echo y | mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt1 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt2'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'echo y | mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt1 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt2' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:19 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:20 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:55:21 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 echo y | mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt1 /dev/vdb vdc vdd vde vdf vdg vdh vdi vdj vdk vdl vdm vdn vdo vdp vdq vdr vds vdt2
root@10.198.114.3's password: 
mdadm: You have listed more devices (38) than are in the array(2)!
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Apr 28 12:55:25 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0 'Create md failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Create md failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Create md failed.'
+ LOG_ERROR 'Create md failed.'
+ message='Create md failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Create md failed.'
Fri Apr 28 12:55:26 2023 - ERROR - Create md failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_auto_mount.sh line 50'
+ message='oe_test_raid_auto_mount.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_auto_mount.sh line 50'
Fri Apr 28 12:55:27 2023 - ERROR - oe_test_raid_auto_mount.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ ssh_cmd_node 'mdadm -Ds | grep /dev/md0'
+ cmd='mdadm -Ds | grep /dev/md0'
+ SSH_CMD 'mdadm -Ds | grep /dev/md0' 10.198.114.3 'openEuler12#$' root
+ cmd='mdadm -Ds | grep /dev/md0'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'mdadm -Ds | grep /dev/md0' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:28 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:29 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:55:30 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 mdadm -Ds | grep /dev/md0
root@10.198.114.3's password: 
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Apr 28 12:55:36 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0 'Check md failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check md failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check md failed.'
+ LOG_ERROR 'Check md failed.'
+ message='Check md failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check md failed.'
Fri Apr 28 12:55:37 2023 - ERROR - Check md failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_auto_mount.sh line 52'
+ message='oe_test_raid_auto_mount.sh line 52'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_auto_mount.sh line 52'
Fri Apr 28 12:55:37 2023 - ERROR - oe_test_raid_auto_mount.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ [[ ext3 == \x\f\s ]]
+ ssh_cmd_node 'echo y | mkfs -t ext3 /dev/md0'
+ cmd='echo y | mkfs -t ext3 /dev/md0'
+ SSH_CMD 'echo y | mkfs -t ext3 /dev/md0' 10.198.114.3 'openEuler12#$' root
+ cmd='echo y | mkfs -t ext3 /dev/md0'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'echo y | mkfs -t ext3 /dev/md0' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:39 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:40 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:55:40 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 echo y | mkfs -t ext3 /dev/md0
root@10.198.114.3's password: 
mke2fs 1.46.5 (30-Dec-2021)
The file /dev/md0 does not exist and no size was specified.
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Apr 28 12:55:46 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0 'mkfs failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='mkfs failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'mkfs failed.'
+ LOG_ERROR 'mkfs failed.'
+ message='mkfs failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mkfs failed.'
Fri Apr 28 12:55:46 2023 - ERROR - mkfs failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_auto_mount.sh line 58'
+ message='oe_test_raid_auto_mount.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_auto_mount.sh line 58'
Fri Apr 28 12:55:47 2023 - ERROR - oe_test_raid_auto_mount.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ ssh_cmd_node 'mount /dev/md0 /mnt/test_md'
+ cmd='mount /dev/md0 /mnt/test_md'
+ SSH_CMD 'mount /dev/md0 /mnt/test_md' 10.198.114.3 'openEuler12#$' root
+ cmd='mount /dev/md0 /mnt/test_md'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'mount /dev/md0 /mnt/test_md' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:48 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:49 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:55:50 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 mount /dev/md0 /mnt/test_md
root@10.198.114.3's password: 
mount: /mnt/test_md: special device /dev/md0 does not exist.
+ ret=32
+ test 32 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:32'
+ message='Failed in remote CMD operation:32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:32'
Fri Apr 28 12:55:55 2023 - ERROR - Failed in remote CMD operation:32
+ return 32
+ CHECK_RESULT 32 0 0 'Mount md failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='Mount md failed.'
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'Mount md failed.'
+ LOG_ERROR 'Mount md failed.'
+ message='Mount md failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Mount md failed.'
Fri Apr 28 12:55:56 2023 - ERROR - Mount md failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_auto_mount.sh line 60'
+ message='oe_test_raid_auto_mount.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_auto_mount.sh line 60'
Fri Apr 28 12:55:57 2023 - ERROR - oe_test_raid_auto_mount.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ ssh_cmd_node 'echo '\''/dev/md0 /mnt/test_md ext3 defaults 0 0'\'' >> /etc/fstab'
+ cmd='echo '\''/dev/md0 /mnt/test_md ext3 defaults 0 0'\'' >> /etc/fstab'
+ SSH_CMD 'echo '\''/dev/md0 /mnt/test_md ext3 defaults 0 0'\'' >> /etc/fstab' 10.198.114.3 'openEuler12#$' root
+ cmd='echo '\''/dev/md0 /mnt/test_md ext3 defaults 0 0'\'' >> /etc/fstab'
+ remoteip=10.198.114.3
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'echo '\''/dev/md0 /mnt/test_md ext3 defaults 0 0'\'' >> /etc/fstab' -i 10.198.114.3 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Apr 28 12:55:58 2023 - WARN  - the remote user uses the default configuration.
Fri Apr 28 12:55:59 2023 - WARN  - the remote password uses the default configuration.
Fri Apr 28 12:56:00 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.198.114.3 echo '/dev/md0 /mnt/test_md ext3 defaults 0 0' >> /etc/fstab
root@10.198.114.3's password: 
+ ret=0
+ test 0 -ne 0
+ return 0
+ REMOTE_REBOOT 2 60
+ node=2
+ waittime=60
+ '[' 60x '!=' x ']'
+ python3 /root/mugen/libs/locallibs/remote_reboot.py reboot --node 2 --waittime 60
Fri Apr 28 12:56:14 2023 - WARN  - Failed to connect the remote machine:10.198.114.3.
Fri Apr 28 12:56:14 2023 - WARN  - [Errno None] Unable to connect to port 22 on 10.198.114.3
Fri Apr 28 13:24:09 2023 - ERROR - Timeout : Command 'bash -x oe_test_raid_auto_mount.sh' timed out after 1799.998837892 seconds
