+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed May  3 01:53:11 2023 - INFO  - Start to prepare the database config.
++ lsblk
++ grep disk
++ awk '{print $1}'
++ tail -n 1
+ free_disk=vdb
+ disk_name=/dev/vdb
++ ls -l /usr/lib/modules
++ awk '{print $9}'
++ tail -n 1
+ kernel_version=6.1.19-7.0.0.17.oe2303.x86_64
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Wed May  3 01:53:11 2023 - INFO  - Finish to prepare the database config.
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed May  3 01:53:11 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL mdadm
+ pkgs=mdadm
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs mdadm --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp0sc2tpsw
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp0sc2tpsw
+ mkdir /mnt/test_md
+ fdisk /dev/vdb

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-41943039, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-41943039, default 41943039): 
Created a new partition 1 of type 'Linux' and of size 47.8 MiB.

Command (m for help): Y: unknown command

Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (2-4, default 2): First sector (100001-41943039, default 100352): Last sector, +/-sectors or +/-size{K,M,G,T,P} (100352-41943039, default 41943039): 
Created a new partition 2 of type 'Linux' and of size 48.7 MiB.

Command (m for help): Y: unknown command

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Wed May  3 01:53:30 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 01:53:30 2023 - INFO  - Start to run test.
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:31 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:31 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 2de31e4d-2bde-423c-ae8a-bf8c67cf7faf
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 1
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 1 /mnt/test_md/testfile1
1
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:32 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:33 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:31 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:31 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 0feda9f3-54a1-4cdf-868f-1ff1eab52f96
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 2
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 2 /mnt/test_md/testfile2
2
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:34 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:34 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:33 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:33 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 6112a906-e9ff-4c57-9801-caf1675d48ce
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 3
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 3 /mnt/test_md/testfile3
3
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:36 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:36 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:34 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:34 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: feae136e-77a2-408b-80fb-1228e561efc7
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 4
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 4 /mnt/test_md/testfile4
4
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:38 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:38 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:36 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:36 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 1c81857f-c01b-4fd4-a049-c72571087f36
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 5
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 5 /mnt/test_md/testfile5
5
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:40 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:40 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:38 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:38 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: e5800160-9025-4b60-9b45-eb3ba12be638
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 6
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 6 /mnt/test_md/testfile6
6
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:41 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:42 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:40 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:40 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 4152c1c4-95f1-4129-95cd-d3eca1ff885a
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 7
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 7 /mnt/test_md/testfile7
7
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:43 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:43 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:42 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:42 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 0661dba6-abed-4034-b982-7ad5a025f89e
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 8
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 8 /mnt/test_md/testfile8
8
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:45 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:45 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:43 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:43 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 4f84df86-1861-4c54-954c-e05a12b918b0
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 9
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 9 /mnt/test_md/testfile9
9
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:47 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:47 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:45 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:45 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 86ae6d11-a231-4323-8822-12d60793c117
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 10
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 10 /mnt/test_md/testfile10
10
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:49 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:49 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:47 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:47 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ mkfs -t ext4 /dev/md0
+ echo y
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 62224580-9cff-4bb7-874f-51412bb0091b
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 11
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 11 /mnt/test_md/testfile11
11
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:51 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:51 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:49 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:49 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: fffedfb7-50cc-4122-9859-f4692616851f
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 12
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 12 /mnt/test_md/testfile12
12
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:52 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:53 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:51 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:51 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 28d70c89-e3f5-4634-953b-c901c6ad75e6
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 13
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 13 /mnt/test_md/testfile13
13
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:54 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:54 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:53 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:53 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 4d8ce739-2a5a-4948-ac2c-605a30365bc1
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 14
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 14 /mnt/test_md/testfile14
14
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:56 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:56 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:54 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:54 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 650db589-8993-4692-ab72-2d75a647ffd2
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 15
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 15 /mnt/test_md/testfile15
15
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:58 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:53:58 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:56 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:56 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 68948e25-3543-4105-a144-fe82b3a44916
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 16
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 16 /mnt/test_md/testfile16
16
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:53:59 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:00 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:58 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:53:58 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 8325054b-d732-4c60-91e6-eb09286844ab
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 17
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 17 /mnt/test_md/testfile17
17
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:01 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:01 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:00 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:00 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ mkfs -t ext4 /dev/md0
+ echo y
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 78e60e0a-19d6-44fa-94e7-795ae541d833
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 18
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 18 /mnt/test_md/testfile18
18
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:03 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:03 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:01 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:01 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 3ff03424-8e6f-4139-bcc4-2f65f58639d4
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 19
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 19 /mnt/test_md/testfile19
19
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:05 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:05 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:03 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:03 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b598d546-30b3-47a1-9c17-3d5c6d2bd434
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 20
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 20 /mnt/test_md/testfile20
20
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:07 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:07 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:05 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:05 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: e85417e0-2a9d-41cc-bd6e-1ae7352bca94
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 21
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 21 /mnt/test_md/testfile21
21
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:08 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:09 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:07 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:07 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 71ed6d58-3572-4b07-afdf-ae8b39126d03
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 22
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 22 /mnt/test_md/testfile22
22
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:10 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:10 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:09 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:09 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: ee31a255-b397-47c6-a110-6cc39dc2d086
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 23
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 23 /mnt/test_md/testfile23
23
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:12 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:12 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:11 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:11 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 76a763e4-63f1-47e5-ab4e-3b945d4edc0a
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 24
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 24 /mnt/test_md/testfile24
24
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:14 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:14 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:12 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:12 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 65c70e34-b051-4aa2-a388-121d841713ff
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 25
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 25 /mnt/test_md/testfile25
25
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:16 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:16 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:14 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:14 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b2162cb1-75e5-423c-9741-f1653bd87469
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 26
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 26 /mnt/test_md/testfile26
26
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:17 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:18 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:16 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:16 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ mkfs -t ext4 /dev/md0
+ echo y
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b385376e-e21b-444f-bb06-a4a04fc8819d
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 27
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 27 /mnt/test_md/testfile27
27
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:19 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:20 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:18 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:18 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b8bdc99e-678a-47f3-9397-8c014635adde
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 28
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 28 /mnt/test_md/testfile28
28
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:21 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:21 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:20 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:20 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 7a903bc1-d993-4175-8186-998d48370275
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 29
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 29 /mnt/test_md/testfile29
29
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:23 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:23 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:21 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:21 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 5061a0f4-13d9-4883-8ad3-3152e27f480a
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 30
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 30 /mnt/test_md/testfile30
30
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:25 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:25 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:23 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:23 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 0eb60fdc-6808-4496-a829-2769b0fff516
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 31
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 31 /mnt/test_md/testfile31
31
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:26 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:27 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:25 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:25 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: f325cb23-2172-4914-981c-0c153610e351
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 32
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 32 /mnt/test_md/testfile32
32
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:28 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:28 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:27 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:27 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: ed1acc19-afb8-483b-bf20-71fa4abd9898
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 33
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 33 /mnt/test_md/testfile33
33
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:30 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:30 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:28 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:28 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: a5b6eec4-1ce3-4f36-bf94-1bc28b04bfe3
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 34
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 34 /mnt/test_md/testfile34
34
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:32 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:32 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:30 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:30 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: ae6303f8-1d59-443a-9c74-db18cabb34ad
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 35
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 35 /mnt/test_md/testfile35
35
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:34 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:34 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:32 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:32 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 77c387bc-ccf7-40ea-bc41-e576ba4667f4
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 36
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 36 /mnt/test_md/testfile36
36
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:35 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:36 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:34 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:34 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 3352f28e-2fa6-4abb-aa7a-fd85eba99b89
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 37
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 37 /mnt/test_md/testfile37
37
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:37 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:38 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:36 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:36 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: a830861b-09ff-4302-b86c-b3594f0e53f7
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 38
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 38 /mnt/test_md/testfile38
38
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:39 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:39 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:38 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:38 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 04692f5c-0fd6-4008-8a69-031988e6dbf5
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 39
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 39 /mnt/test_md/testfile39
39
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:41 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:41 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:39 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:39 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b08bd1c3-c833-42db-93cd-7b71876fffa2
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 40
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 40 /mnt/test_md/testfile40
40
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:43 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:43 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:41 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:41 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: e3e77e49-e86b-43c9-9192-c43371f35e3c
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/61/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 41
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 41 /mnt/test_md/testfile41
41
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:44 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:45 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:43 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:43 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 5ebcb3c1-34b0-44e5-bd10-4cf42a0905ee
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 42
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 42 /mnt/test_md/testfile42
42
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:46 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:46 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:45 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:45 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: 641fa076-3f00-4e4e-955b-04ffe657525a
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 43
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 43 /mnt/test_md/testfile43
43
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:48 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:48 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:47 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:47 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b0fb983a-f1bc-419d-b02a-ee6e972d8224
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 44
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 44 /mnt/test_md/testfile44
44
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:50 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:50 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:48 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:48 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ mkfs -t ext4 /dev/md0
+ echo y
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: d06e9e65-e8b9-47ec-b8af-93b6f7e70408
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 45
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 45 /mnt/test_md/testfile45
45
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:52 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:52 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:50 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:50 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: eb6f270c-1bf7-4bff-a9dc-b6613c4ff936
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 46
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 46 /mnt/test_md/testfile46
46
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:54 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:54 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:52 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:52 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: a150c9fa-a43d-4297-97f8-ff39e30b379d
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 47
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 47 /mnt/test_md/testfile47
47
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:55 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:56 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:54 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:54 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: b409ad9b-a5b6-4e64-b727-7308de5fe238
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 48
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 48 /mnt/test_md/testfile48
48
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:57 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:57 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:56 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:56 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: a44671e6-e7ce-4fe1-bc41-c3f3ee6549d5
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 49
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 49 /mnt/test_md/testfile49
49
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ for i in {1..50}
+ rmmod raid1
+ CHECK_RESULT 0 0 0 'Remove mode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Remove mode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ insmod /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko
insmod: ERROR: could not load module /usr/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kernel/drivers/md/raid1.ko: No such file or directory
+ CHECK_RESULT 1 0 0 'Add mode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Add mode failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Add mode failed.'
+ LOG_ERROR 'Add mode failed.'
+ message='Add mode failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Add mode failed.'
Wed May  3 01:54:59 2023 - ERROR - Add mode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_raid_rm_ko.sh line 57'
+ message='oe_test_raid_rm_ko.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_raid_rm_ko.sh line 57'
Wed May  3 01:54:59 2023 - ERROR - oe_test_raid_rm_ko.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ echo y
+ mdadm -C -v /dev/md0 -l 1 -n 2 /dev/vdb1 /dev/vdb2
mdadm: /dev/vdb1 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:57 2023
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
mdadm: /dev/vdb2 appears to be part of a raid array:
       level=raid1 devices=2 ctime=Wed May  3 01:54:57 2023
mdadm: size set to 47936K
mdadm: largest drive (/dev/vdb2) exceeds size (47936K) by more than 1%
Continue creating array? mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
+ echo y
+ mkfs -t ext4 /dev/md0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:     0/47936           done                            
Creating filesystem with 47936 1k blocks and 12000 inodes
Filesystem UUID: a7b61602-47e7-42d6-96ce-13d0ad295bdf
Superblock backups stored on blocks: 
	8193, 24577, 40961

Allocating group tables: 0/6   done                            
Writing inode tables: 0/6   done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/6   done

+ mount /dev/md0 /mnt/test_md
+ echo 50
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 50 /mnt/test_md/testfile50
50
+ CHECK_RESULT 0 0 0 'Read file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Read file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount /dev/md0
+ mdadm --stop /dev/md0
mdadm: stopped /dev/md0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed May  3 01:55:01 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 50
+ test 50 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed May  3 01:55:01 2023 - ERROR - failed to execute the case.
+ exit 50
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 01:55:01 2023 - INFO  - Start to restore the test environment.
+ rm -rf /mnt/test_md
+ mdadm --misc --zero-superblock /dev/vdb1
+ mdadm --misc --zero-superblock /dev/vdb2
+ fdisk /dev/vdb

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition number (1,2, default 2): 
Partition 2 has been deleted.

Command (m for help): Selected partition 1
Partition 1 has been deleted.

Command (m for help): 

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Device or resource busy

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or partx(8).

+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp0sc2tpsw ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp0sc2tpsw
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed May  3 01:55:07 2023 - INFO  - End to restore the test environment.
