+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Wed May  3 04:48:13 2023 - INFO  - Start environment preparation.
+ point_list=($(CREATE_FS))
++ CREATE_FS
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230503044813
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230503044813
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vdb
+++ disk_name=/dev/vdb
+++ pvcreate /dev/vdb -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vdb
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230503044813
++ point=/tmp/point120230503044813
++ lvcreate -n test_lv120230503044813 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230503044813
mke2fs 1.46.5 (30-Dec-2021)
The file /dev//test_lv120230503044813 does not exist and no size was specified.
++ mkdir /tmp/point120230503044813
++ mount /dev//test_lv120230503044813 /tmp/point120230503044813
mount: /tmp/point120230503044813: special device /dev//test_lv120230503044813 does not exist.
++ msg=' /tmp/point120230503044813 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230503044813
++ point=/tmp/point220230503044813
++ lvcreate -n test_lv220230503044813 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230503044813
mke2fs 1.46.5 (30-Dec-2021)
The file /dev//test_lv220230503044813 does not exist and no size was specified.
++ mkdir /tmp/point220230503044813
++ mount /dev//test_lv220230503044813 /tmp/point220230503044813
mount: /tmp/point220230503044813: special device /dev//test_lv220230503044813 does not exist.
++ msg=' /tmp/point120230503044813 /tmp/point220230503044813 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230503044813
++ point=/tmp/point320230503044813
++ lvcreate -n test_lv320230503044813 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230503044813
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230503044813
++ mount /dev//test_lv320230503044813 /tmp/point320230503044813
mount: /tmp/point320230503044813: special device /dev//test_lv320230503044813 does not exist.
++ msg=' /tmp/point120230503044813 /tmp/point220230503044813 /tmp/point320230503044813 '
++ count=4
++ echo /tmp/point120230503044813 /tmp/point220230503044813 /tmp/point320230503044813
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed May  3 04:48:15 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 04:48:15 2023 - INFO  - Start to run test.
++ seq 1 2
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ point=/tmp/point220230503044813
+ mkdir /tmp/point220230503044813/testdir
+ stat /tmp/point220230503044813/testdir
+ grep Inode
Device: 0,44	Inode: 23          Links: 2
+ CHECK_RESULT 0 0 0 'The stat info on /tmp/point220230503044813 has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The stat info on /tmp/point220230503044813 has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ point=/tmp/point320230503044813
+ mkdir /tmp/point320230503044813/testdir
+ stat /tmp/point320230503044813/testdir
+ grep Inode
Device: 0,44	Inode: 24          Links: 2
+ CHECK_RESULT 0 0 0 'The stat info on /tmp/point320230503044813 has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The stat info on /tmp/point320230503044813 has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ stat --help
+ grep Usage
Usage: stat [OPTION]... FILE...
+ CHECK_RESULT 0 0 0 'The help of stat has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The help of stat has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed May  3 04:48:16 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Wed May  3 04:48:16 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 04:48:16 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230503044813 /tmp/point220230503044813 /tmp/point320230503044813
+ list='/tmp/point120230503044813 /tmp/point220230503044813 /tmp/point320230503044813'
+ REMOVE_FS '/tmp/point120230503044813 /tmp/point220230503044813 /tmp/point320230503044813'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230503044813
++ df -T
++ grep /tmp/point120230503044813
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230503044813
++ df -T
++ grep /tmp/point220230503044813
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230503044813
++ df -T
++ grep /tmp/point320230503044813
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed May  3 04:48:16 2023 - INFO  - End to restore the test environment.
